name: build and deploy cicd # adding comment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.2'        

      - name: Build with Maven
        run: mvn clean install  
        
      - name: Login into ECR container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} 

      - name: Tagging docker image
        run: docker build -t 309788354422.dkr.ecr.eu-central-1.amazonaws.com/av-test:latest .

      - name: Push image to ECR container registry
        run: docker push 309788354422.dkr.ecr.eu-central-1.amazonaws.com/av-test:latest

