name: build and deploy cicd # adding comment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.2'        

      - name: Build with Maven
        run: mvn clean install  

      - name: Adding repo git tag env variable
        run: echo "CI_COMMIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV 

      - name: Add SHORT_SHA env variable
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV 
        
      - name: Login into ECR container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} 

      - name: Tagging docker image
        run: docker build -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_PROJECT }}/:${CI_COMMIT_TAG}-${SHORT_SHA} .

      - name: Push image to ECR container registry
        run: docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_PROJECT }}/:${CI_COMMIT_TAG}-${SHORT_SHA}
        

